### ISSUE TITLE
bug: rerank example got an error

### ISSUE THREAD

**Issue by miaojinc** [mosecorg/mosec#535]
### Describe the bug

I try to use mosec's rerank [example ](https://mosecorg.github.io/mosec/examples/rerank.html), but the server got error:
For mosec==0.8.5, the error is:
```
2024-06-15T00:55:54.001558Z  WARNING mosec::coordinator.py:300 [1869971]: Traceback (most recent call last):
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 274, in coordinate     data = [
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 275, in <listcomp>     self.decode(payload, state)
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 243, in decode     self.worker.deserialize(payload)
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/mixin/typed_worker.py", line 45, in deserialize     return msgspec.msgpack.decode(data, type=self._input_typ)
   TypeError: Type ''Request'' is not supported
```

For mosec==0.8.4, the error is:
```
2024-06-15T01:12:16.381367Z  WARNING mosec::coordinator.py:300 [1872350]: Traceback (most recent call last):
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 274, in coordinate     data = [
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 275, in <listcomp>     self.decode(payload, state)
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/coordinator.py", line 243, in decode     self.worker.deserialize(payload)
   File "/home/user/mosec/lib/python3.10/site-packages/mosec/mixin/typed_worker.py", line 43, in deserialize     if not issubclass(self._input_typ, msgspec.Struct):
   TypeError: issubclass() arg 1 must be a class
```

### To Reproduce

pip install mosec
use the code from https://mosecorg.github.io/mosec/examples/rerank.html
python server.py
python client.py

### Expected behavior

no error, client got the ranked result

### The mosec version

0.8.5, 0.8.4

**Comment by kemingy** [comment]
Thanks for your feedback. It is related to the OpenAPI spec generation. This is due to the Python type annotation lazy evaluation. I'll create a PR to enable the `inspect.get_annotations(eval=True)` for all the supported Python version (>=3.8).
